# File: compose.yaml
# Description: Docker Compose file for HDMI Assistant Node. Manage the service once the image has been built.
# Author: Chuffnugget

services:
  hdmi-assistant-node:
    build: .
    privileged: true
    volumes:
      - /dev:/dev
    env_file:
      - .env
    environment:
      - HA_URL
      - HA_TOKEN
      - POLL_INTERVAL
    #network_mode: host     # ← host networking so mDNS (zeroconf) discovery works; change/remove for bridge mode (auto-discovery disabled)
    ports:
      - "8000:8000"        # host:container port mapping (ignored in host mode but kept for clarity)
    restart: unless-stopped
