# File: compose.yaml
# Description: Docker Compose file for BrightDock Core. This should be used to manage the service once the image has been built.
# Author: Chuffnugget

services:
  brightdock-core:
    build: .
    privileged: true
    volumes:
      - /dev:/dev
    env_file:
      - .env
    environment:
      - HA_URL
      - HA_TOKEN
      - POLL_INTERVAL
    ports:
      - "8000:8000"
    restart: unless-stopped

