# File: compose.yaml
# Description: Docker Compose file for HDMI Assistant Node. Manage the service once the image has been built.
# Author: Chuffnugget

services:
  hdmi-assistant-node:             
    build: .
    privileged: true
    volumes:
      - /dev:/dev
    env_file:
      - .env
    environment:
      - HA_URL
      - HA_TOKEN
      - POLL_INTERVAL
    ports:
      - "8000:8000"                # host:container
    restart: unless-stopped
